swagger: "2.0"
info:
  title: DeWeb Read API
  description: DeWeb API used to browse decentralized websites
  version: 0.1.0

schemes:
  - http
paths:
  /{resource}:
    get:
      operationId: getResource
      parameters:
        - name: resource
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Resource not found
          schema:
            $ref: "#/definitions/Error"
  /:
    get:
      operationId: defaultPage
      responses:
        "200":
          description: Shows the default page
  
  /__deweb_info:
    get:
      operationId: getDeWebInfo
      produces:
        - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: "#/definitions/DeWebInfo"

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
  DeWebInfo:
    type: object
    properties:
      app:
        type: string
      version:
        type: string
      misc:
        type: object
        additionalProperties: true
      network:
        type: object
        properties:
          network:
            type: string
          version:
            type: string
          chainID:
            type: integer
            format: int64
      allowList:
        type: array
        items:
          type: string
      blockList:
        type: array
        items:
          type: string