version: "3"

tasks:
  install:
    cmds:
      # Empty for now

  generate:
    cmds:
      - cmd: go generate ./...

  build:
    cmds:
      - task: build:server
      - task: build:cli

  build:internal:
    build:
    desc: Internal build task
    internal: true
    cmds:
      - cmd: echo Building DeWeb {{.APP_NAME}} for {{.OS | default OS}}/{{.ARCH | default ARCH}}
        silent: true
      - cmd: 'echo Mode: {{if eq .PRODUCTION "true"}}Production{{else}}Development{{end}}'
        silent: true
      - cmd: 'echo Version: {{.VERSION | default "Development"}}'
        silent: true
      - cmd: go build {{.BUILD_FLAGS}} -o {{.BIN_DIR}}/{{.APP_NAME}}{{.BIN_EXT}} ./cmd/{{.APP_NAME}}
    vars:
      # We need this check for nil and empty string because a simple check for empty string doesn't work as expected
      VERSION_FLAG: '{{if ne .VERSION nil}}{{if ne .VERSION ""}}-X github.com/massalabs/DeWeb/int/config.Version=v{{.VERSION}}{{end}}{{end}}'
      BUILD_FLAGS: '{{if eq .PRODUCTION "true"}}-tags production {{end}}-ldflags="{{.VERSION_FLAG}}{{if eq .PRODUCTION "true"}} -w -s{{end}}"'
      BIN_EXT: '{{if eq .OS "windows"}}.exe{{end}}'
    env:
      GOOS: "{{.OS | default OS}}"
      GOARCH: "{{.ARCH | default ARCH}}"
      PRODUCTION: '{{.PRODUCTION | default "false"}}'
      VERSION: "{{.VERSION | default nil}}"

  build:server:
    cmds:
      - task: build:internal
        vars:
          APP_NAME: server
          BIN_DIR: build

  build:cli:
    cmds:
      - task: build:internal
        vars:
          APP_NAME: cli
          BIN_DIR: build

  run:cli:
    cmds:
      - cmd: ./build/cli

  run:server:
    cmds:
      - cmd: ./build/server

  clean:
    cmds:
      - cmd: rm -rf build

  test:
    cmds:
      - cmd: go test ./...

  install:tools:
    cmds:
      - cmd: go install mvdan.cc/gofumpt@latest
      - cmd: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  lint:
    cmds:
      - cmd: golangci-lint run

  fmt:
    cmds:
      - cmd: go mod tidy
      - cmd: gofumpt -l -w .
      - cmd: gci write .
      - cmd: golangci-lint run --fix
