// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DefaultPageFoundCode is the HTTP code returned for type DefaultPageFound
const DefaultPageFoundCode int = 302

/*
DefaultPageFound Redirect to /web

swagger:response defaultPageFound
*/
type DefaultPageFound struct {
}

// NewDefaultPageFound creates DefaultPageFound with default headers values
func NewDefaultPageFound() *DefaultPageFound {

	return &DefaultPageFound{}
}

// WriteResponse to the client
func (o *DefaultPageFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(302)
}
