// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/deweb-plugin/api/models"
)

// GetSettingsOKCode is the HTTP code returned for type GetSettingsOK
const GetSettingsOKCode int = 200

/*
GetSettingsOK Current settings

swagger:response getSettingsOK
*/
type GetSettingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Settings `json:"body,omitempty"`
}

// NewGetSettingsOK creates GetSettingsOK with default headers values
func NewGetSettingsOK() *GetSettingsOK {

	return &GetSettingsOK{}
}

// WithPayload adds the payload to the get settings o k response
func (o *GetSettingsOK) WithPayload(payload *models.Settings) *GetSettingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get settings o k response
func (o *GetSettingsOK) SetPayload(payload *models.Settings) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSettingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
