// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/massalabs/deweb-plugin/api/models"
)

// GetServerStatusOKCode is the HTTP code returned for type GetServerStatusOK
const GetServerStatusOKCode int = 200

/*
GetServerStatusOK Current server status

swagger:response getServerStatusOK
*/
type GetServerStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.ServerStatus `json:"body,omitempty"`
}

// NewGetServerStatusOK creates GetServerStatusOK with default headers values
func NewGetServerStatusOK() *GetServerStatusOK {

	return &GetServerStatusOK{}
}

// WithPayload adds the payload to the get server status o k response
func (o *GetServerStatusOK) WithPayload(payload *models.ServerStatus) *GetServerStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get server status o k response
func (o *GetServerStatusOK) SetPayload(payload *models.ServerStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetServerStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
