// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PluginWebAppHandlerFunc turns a function with the right signature into a plugin web app handler
type PluginWebAppHandlerFunc func(PluginWebAppParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PluginWebAppHandlerFunc) Handle(params PluginWebAppParams) middleware.Responder {
	return fn(params)
}

// PluginWebAppHandler interface for that can handle valid plugin web app params
type PluginWebAppHandler interface {
	Handle(PluginWebAppParams) middleware.Responder
}

// NewPluginWebApp creates a new http.Handler for the plugin web app operation
func NewPluginWebApp(ctx *middleware.Context, handler PluginWebAppHandler) *PluginWebApp {
	return &PluginWebApp{Context: ctx, Handler: handler}
}

/*
	PluginWebApp swagger:route GET /web/{resource} pluginWebApp

Plugin Frontend router.
*/
type PluginWebApp struct {
	Context *middleware.Context
	Handler PluginWebAppHandler
}

func (o *PluginWebApp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPluginWebAppParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
