// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RedirectToWebHandlerFunc turns a function with the right signature into a redirect to web handler
type RedirectToWebHandlerFunc func(RedirectToWebParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RedirectToWebHandlerFunc) Handle(params RedirectToWebParams) middleware.Responder {
	return fn(params)
}

// RedirectToWebHandler interface for that can handle valid redirect to web params
type RedirectToWebHandler interface {
	Handle(RedirectToWebParams) middleware.Responder
}

// NewRedirectToWeb creates a new http.Handler for the redirect to web operation
func NewRedirectToWeb(ctx *middleware.Context, handler RedirectToWebHandler) *RedirectToWeb {
	return &RedirectToWeb{Context: ctx, Handler: handler}
}

/*
	RedirectToWeb swagger:route GET / redirectToWeb

Redirect to the web interface
*/
type RedirectToWeb struct {
	Context *middleware.Context
	Handler RedirectToWebHandler
}

func (o *RedirectToWeb) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRedirectToWebParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
