// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RedirectToWebFoundCode is the HTTP code returned for type RedirectToWebFound
const RedirectToWebFoundCode int = 302

/*
RedirectToWebFound Redirect to /web

swagger:response redirectToWebFound
*/
type RedirectToWebFound struct {
}

// NewRedirectToWebFound creates RedirectToWebFound with default headers values
func NewRedirectToWebFound() *RedirectToWebFound {

	return &RedirectToWebFound{}
}

// WriteResponse to the client
func (o *RedirectToWebFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(302)
}
