// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/massalabs/deweb-plugin/api/models"
)

// NewUpdateSettingsParams creates a new UpdateSettingsParams object
//
// There are no default values defined in the spec.
func NewUpdateSettingsParams() UpdateSettingsParams {

	return UpdateSettingsParams{}
}

// UpdateSettingsParams contains all the bound params for the update settings operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateSettings
type UpdateSettingsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*New settings
	  Required: true
	  In: body
	*/
	Settings *models.Settings
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateSettingsParams() beforehand.
func (o *UpdateSettingsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Settings
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("settings", "body", ""))
			} else {
				res = append(res, errors.NewParseError("settings", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Settings = &body
			}
		}
	} else {
		res = append(res, errors.Required("settings", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
