// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateSettingsHandlerFunc turns a function with the right signature into a update settings handler
type UpdateSettingsHandlerFunc func(UpdateSettingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSettingsHandlerFunc) Handle(params UpdateSettingsParams) middleware.Responder {
	return fn(params)
}

// UpdateSettingsHandler interface for that can handle valid update settings params
type UpdateSettingsHandler interface {
	Handle(UpdateSettingsParams) middleware.Responder
}

// NewUpdateSettings creates a new http.Handler for the update settings operation
func NewUpdateSettings(ctx *middleware.Context, handler UpdateSettingsHandler) *UpdateSettings {
	return &UpdateSettings{Context: ctx, Handler: handler}
}

/*
	UpdateSettings swagger:route PUT /api/settings updateSettings

Update plugin settings
*/
type UpdateSettings struct {
	Context *middleware.Context
	Handler UpdateSettingsHandler
}

func (o *UpdateSettings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateSettingsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
