// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NetworkInfoItem Detailed network information
//
// swagger:model NetworkInfoItem
type NetworkInfoItem struct {

	// chain Id
	ChainID int64 `json:"chainId,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// status
	// Enum: ["up","down"]
	Status string `json:"status,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this network info item
func (m *NetworkInfoItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var networkInfoItemTypeStatusPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["up","down"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		networkInfoItemTypeStatusPropEnum = append(networkInfoItemTypeStatusPropEnum, v)
	}
}

const (

	// NetworkInfoItemStatusUp captures enum value "up"
	NetworkInfoItemStatusUp string = "up"

	// NetworkInfoItemStatusDown captures enum value "down"
	NetworkInfoItemStatusDown string = "down"
)

// prop value enum
func (m *NetworkInfoItem) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, networkInfoItemTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *NetworkInfoItem) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this network info item based on context it is used
func (m *NetworkInfoItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkInfoItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkInfoItem) UnmarshalBinary(b []byte) error {
	var res NetworkInfoItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
