// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Settings settings
//
// swagger:model Settings
type Settings struct {

	// cache
	Cache *CacheSettings `json:"cache,omitempty"`

	// The network node URL to connect to
	// Required: true
	NetworkURL *string `json:"networkUrl"`

	// The port the server is running on
	ServerPort int32 `json:"serverPort,omitempty"`
}

// Validate validates this settings
func (m *Settings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCache(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Settings) validateCache(formats strfmt.Registry) error {
	if swag.IsZero(m.Cache) { // not required
		return nil
	}

	if m.Cache != nil {
		if err := m.Cache.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cache")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cache")
			}
			return err
		}
	}

	return nil
}

func (m *Settings) validateNetworkURL(formats strfmt.Registry) error {

	if err := validate.Required("networkUrl", "body", m.NetworkURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this settings based on the context it is used
func (m *Settings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCache(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Settings) contextValidateCache(ctx context.Context, formats strfmt.Registry) error {

	if m.Cache != nil {

		if swag.IsZero(m.Cache) { // not required
			return nil
		}

		if err := m.Cache.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cache")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cache")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Settings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Settings) UnmarshalBinary(b []byte) error {
	var res Settings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
