name: Install

inputs:
  os:
    description: The operating system to run the action on, should be the 'runs-on' in workflows
    required: true
    default: "ubuntu-22.04"
  repo-token:
    description: The token to use to authenticate with the GitHub API
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22
        cache: true

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.repo-token }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: pages/package-lock.json

    - name: Install Dependencies
      run: task install
      shell: bash

    - name: Generate
      run: task generate
      shell: bash
