export const colors = {
  greenNeon: "#00FF6D",
  blueBright: "#0043FF",
  darkForestGreen: "#043D1B",
  deepNavyBlue: "#030D23",
  yellowBright: "#FFFF00",
  magentaBright: "#E600FF",
  darkOliveGreen: "#1E1D03",
  darkPurple: "#160119",
  redBright: "#FF003D",
  cyanBright: "#00FFCE",
  darkMaroon: "#2D000D",
  darkTeal: "#001E18",
  orangeBright: "#FF7300",
  purpleRoyal: "#5218EF",
  darkBrown: "#3F1B00",
  midnightBlue: "#070021",
  charcoal: "#0C0C0C",
  pinkNeon: "#FF36AE",
  plum: "#661047",
  pastelPink: "#FFE1F4",
  DeepBlue: "#0000A8",
  CelestialMist: "#ECECEC"
};

export const themeNames = [
  "neon_green_forest",
  "bright_blue_navy",
  "sunny_magenta",
  "magenta_sunny",
  "olive_sunshine",
  "magenta_midnight",
  "red_cyan",
  "cyan_red",
  "maroon_red",
  "teal_cyan",
  "sunset_purple",
  "purple_sunset",
  "brown_sunset",
  "midnight_purple",
  "charcoal_neon_pink",
  "neon_pink_charcoal",
  "plum_neon_pink",
  "pastel_neon_pink",
  "light_gray_blue",
  "deep_blue_gray"
];
