// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DefaultPageOKCode is the HTTP code returned for type DefaultPageOK
const DefaultPageOKCode int = 200

/*
DefaultPageOK Shows the default page

swagger:response defaultPageOK
*/
type DefaultPageOK struct {
}

// NewDefaultPageOK creates DefaultPageOK with default headers values
func NewDefaultPageOK() *DefaultPageOK {

	return &DefaultPageOK{}
}

// WriteResponse to the client
func (o *DefaultPageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
