// Code generated by go-swagger; DO NOT EDIT.

// Package restapi DeWeb Plugin API
//
//	API for the DeWeb Plugin in MassaStation
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - text/css
//	  - text/html
//	  - text/javascript
//	  - application/json
//	  - text/webp
//
// swagger:meta
package restapi
