// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeWebInfo de web info
//
// swagger:model DeWebInfo
type DeWebInfo struct {

	// app
	App string `json:"app,omitempty"`

	// misc
	Misc interface{} `json:"misc,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this de web info
func (m *DeWebInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this de web info based on context it is used
func (m *DeWebInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeWebInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeWebInfo) UnmarshalBinary(b []byte) error {
	var res DeWebInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
