name: Npm nightly publish

on:
  push:
    branches: [main]

jobs:
  publish-npm-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - run: ./.github/scripts/publish-cli-dev.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
