name: NPM Publish latest

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: ./.github/scripts/publish-cli.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
