name: Release DeWeb

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for this release (without v prefix)'
        required: true
        type: string
      release-as-draft:
        description: "Whether it's a draft or not"
        required: true
        type: boolean
        default: true
      release-as-prerelease:
        description: "Whether it's a prerelease or not"
        required: true
        type: boolean
        default: false
      generate-release-notes:
        description: "Generate release notes"
        required: true
        type: boolean
        default: true

jobs:
  check-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check the manifest version
        working-directory: ./plugin
        run: |
          sudo apt-get install -y jq
          version=$(jq -r '.version' manifest.json)
          input_version=${{ inputs.version }}
          if [[ "$version" != "$input_version" ]]; then
            echo "ERROR: The manifest version ($version) does not match the input version ($input_version)"
            exit 1
          fi
          echo "Manifest version matches input version: $version"

  build-server:
    needs: check-manifest
    uses: ./.github/workflows/server.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  build-plugin:
    needs: build-server
    uses: ./.github/workflows/plugin.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  create-release:
    needs: [build-server, build-plugin]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download server artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/server
          pattern: 'deweb-server_*'

      - name: Download plugin zip packages
        uses: actions/download-artifact@v4
        with:
          path: artifacts/plugin
          pattern: 'deweb-plugin_*_zip'

      - name: ls -la artifacts/server
        run: ls -la artifacts/server

      - name: ls -la artifacts/plugin
        run: ls -la artifacts/plugin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: DeWeb v${{ inputs.version }}
          draft: ${{ inputs.release-as-draft }}
          prerelease: ${{ inputs.release-as-prerelease }}
          generate_release_notes: ${{ inputs.generate-release-notes }}
          files: |
            artifacts/server/deweb-server_*/deweb-server_*
            artifacts/plugin/deweb-plugin_*_zip/deweb-plugin_*.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.MS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MS_S3_SECRET_ACCESS_KEY }}

      - name: s3 Upload
        env:
          AWS3: ${{ vars.MS_S3_BUCKET }}
          TAG: v${{ inputs.version }}
        run: aws s3 cp artifacts/plugin/deweb-plugin_*_zip/deweb-plugin_*.zip s3://${AWS3}/plugins/deweb/${TAG}/
