name: Server Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Server version for this release (without v prefix)'
        required: true
        type: string
      release-as-draft:
        description: "Whether it's a draft or not"
        required: true
        type: boolean
        default: true
      release-as-prerelease:
        description: "Whether it's a prerelease or not"
        required: true
        type: boolean
        default: false
      generate-release-notes:
        description: "Generate release notes"
        required: true
        type: boolean
        default: true
  
jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ inputs.version }}
    steps:
      - name: Set version
        id: get-version
        run: |
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "Server Version: ${{ inputs.version }}"

  build-server:
    uses: ./.github/workflows/server.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit

  create-release:
    needs: [extract-version, build-server]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all server artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: 'deweb-server_*'

      - name: List artifacts
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.extract-version.outputs.version }}
          name: server v${{ needs.extract-version.outputs.version }}
          draft: ${{ inputs.release-as-draft }}
          prerelease: ${{ inputs.release-as-prerelease }}
          generate_release_notes: ${{ inputs.generate-release-notes }}
          files: |
            artifacts/deweb-server_*/deweb-server_*
