// Code generated by go-swagger; DO NOT EDIT.

// Package restapi DeWeb Read API
//
//	DeWeb API used to browse decentralized websites
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
